### ISSUE TITLE
llama3:instruct nan

### ISSUE THREAD

**Issue by falmanna** [srikanth235/benchllama#2]
Running the benchmark against llama3 is returning `nan`  for all rates

**Comment by LearningisOP** [comment]
Same here

**Comment by srikanth235** [comment]
Currently, benchllama supports evaluating FIM models. Will try to add eval support for instruct fine-tuned models soon. Hope this clarifies the confusion.

**Comment by falmanna** [comment]
@srikanth235 thanks for the work!

I did actually run it successfully against multiple instruct fine-tunes models, is there a difference between them and llama3:instruct?
- codellama:13b-instruct
- mistral:7b-instruct 
- solar:10.7b-instruct-v1-q4_1

**Comment by falmanna** [comment]
okay seems like things are working fine now, might have been an ollama problem. Closing.
